-- Firebase -> Supabase migration script
-- Generated from Codeshastra Export.json

BEGIN;

-- 1) checkpoints
INSERT INTO checkpoints (checkpoint_real_name, title, description, day, time)
VALUES
  ('registration', 'Registration', 'Your journey begins here!', 1, '7:30 am - 8:30 am'),
  ('lunch-day1', 'Lunch', 'Kickstart with a power-packed meal!', 1, '1:30 pm'),
  ('evening_snacks-day1', 'Evening Snacks', 'Satisfy your cravings!', 1, '5:30 pm'),
  ('dinner-day1', 'Dinner', 'Dine and connect!', 1, '8:00 pm'),
  ('midnight_refreshments-day1', 'Midnight Snacks', 'Midnight munchies for night owls!', 1, '2:00 am'),
  ('breakfast-day2', 'Breakfast', 'Refuel for an exciting afternoon!', 2, '7:30 am'),
  ('lunch-day2', 'Lunch', 'Power up for the showdown!', 2, '2:30 pm'),
  ('mentoring-round1', 'Mentoring Round 1', 'Gain insights from mentors!', 1, '3:30 pm'),
  ('mentoring-round2', 'Mentoring Round 2', 'Another round of guidance!', 1, '11:00 pm'),
  ('judging-round1', 'Judging Round 1', 'Who''ll impress in round one?', 2, '10:30 am - 1:30 pm'),
  ('judging-round2', 'Judging Round 2', 'Final showdown!', 2, '3:00 pm - 5:00 pm')
ON CONFLICT (checkpoint_real_name) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    day = EXCLUDED.day,
    time = EXCLUDED.time;

-- 2) criteria
INSERT INTO criteria (name)
SELECT v.name
FROM (VALUES
  ('Innovation'),
  ('Functionality'),
  ('Presentation'),
  ('Feasibility'),
  ('UI/UX')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM criteria c WHERE c.name = v.name);

-- 3) admins
INSERT INTO admins (name, email, password, position, edit_access, view_result_access)
VALUES
  ('Priyansh Shah', 'shah.priyansh04@gmail.com', 'N9Gn', 'VCP Tech', TRUE, TRUE),
  ('Harshil Shah', 'harshilshah0504@gmail.com', 'mhcg', 'Chairperson', FALSE, TRUE),
  ('Sean Rumao', 'seanrumao321@gmail.com', 'GnaN', 'VCP Admin', FALSE, TRUE),
  ('Meet Jain', 'lodhameetr@gmail.com', '6VcG', 'Treasurer', FALSE, TRUE),
  ('Dharmil Parekh', 'dharmilparekh1511@gmail.com', 'BSjh', 'Treasurer', FALSE, TRUE),
  ('Anvaya Solanki', 'anvayasolanki@gmail.com', 'GzSM', 'Secretary', FALSE, TRUE),
  ('Mahek Patel', 'patelmahek1394@gmail.com', 'r0C4', 'Secretary', FALSE, TRUE),
  ('Lakshya Joshi', 'lakshyaj690@gmail.com', '2iiV', 'Marketing Head', FALSE, TRUE),
  ('Divam Sanghvi', 'divamsanghvi@gmail.com', 'oCUl', 'Marketing head', FALSE, TRUE),
  ('Maithili Divecha', 'divechamaithili@gmail.com', 'ufJa', 'Marketing Head', FALSE, TRUE),
  ('Ayush Upadhyay', 'ayush.up105@gmail.com', 'ufWv', 'Tech Head', FALSE, TRUE),
  ('Srinath Reddy', 'srinathreddy239@gmail.com', 'igSG', 'Tech Head', TRUE, TRUE),
  ('Dhvani Shah', 'dhvanishah140304@gmail.com', 'GEv1', 'Events Head', FALSE, FALSE),
  ('Yash Madhani', 'yashmadhani2810@gmail.com', 'brsn', 'Events Head', FALSE, FALSE),
  ('Mohammed Parkar', 'mohammedparkar68@gmail.com', 'fJNc', 'Creatives Head', FALSE, FALSE),
  ('Nivi Bokadia', 'nivibokadia@gmail.com', 'v3PF', 'Creatives Head', FALSE, FALSE),
  ('Ashish Satavase', 'ashishsatavase13@gmail.com', 'UKoM', 'Editorial Head', FALSE, FALSE),
  ('Kanishk Maheshwari', 'maheshwarikanishk2005@gmail.com', 'JNhU', 'Editorial Head', FALSE, FALSE),
  ('Kaivan Shah', 'kaivanshah292@gmail.com', 'e6ES', 'Publicity head', FALSE, FALSE),
  ('Nitika Jain', 'nitikanitinjain@gmail.com', 'nCuH', 'Publicity head', FALSE, FALSE),
  ('Mitul Shah', 'mitulshah8104@gmail.com', 'o6QA', 'Logistics Head', FALSE, FALSE),
  ('Yash Asgaonkar', 'yash240904@gmail.com', 'MCQL', 'Logistics Head', FALSE, FALSE),
  ('Dikshant Badawadagi', 'dikshantbadawadagi@gmail.com', 'bOPz', 'Trinity Co-ordinator', FALSE, FALSE),
  ('Taksh Shah', 'taksh1816@gmail.com', 'YvIy', 'NSS Co-ordinator', FALSE, FALSE),
  ('Rishi Panchal', 'rishibpanchal006@gmail.com', 'cg0u', 'Creatives Co-Comm', FALSE, FALSE),
  ('Hiren Waghela', 'waghelahiren16@gmail.com', '5YZf', 'Creatives Co-Comm', FALSE, FALSE),
  ('Rachit Chotalia', 'rachitchotalia99@gmail.com', 'S2Hb', 'Creatives Co-Comm', FALSE, FALSE),
  ('Aaryan Khanna', 'aaryanhkhanna@gmail.com', 'tg9A', 'Creatives Co-Comm', FALSE, FALSE),
  ('Manan Shah', 'mananshahstudios1@gmail.com', 'jzIP', 'Creatives Co-Comm', FALSE, FALSE),
  ('Diya Panchal', 'diyakpanchal0405@gmail.com', 'Hb9g', 'Creatives Co-Comm', FALSE, FALSE),
  ('Arpit Doshi', 'doshiarpit2005@gmail.com', 'boSV', 'Creatives Co-Comm', FALSE, FALSE),
  ('Yashvi Mehta', 'yashvi.h.mehta235@gmail.com', 'ZWnt', 'Creatives Co-Comm', FALSE, FALSE),
  ('Tanvi Kamath', 'tanvikamath22@gmail.com', 'EzrC', 'Edi Co-Comm', FALSE, FALSE),
  ('Pranav Agarwal', 'pranavagarwal2073@gmail.com', 'rhaG', 'Editorial Co-Comm', FALSE, FALSE),
  ('Nandini Nema', 'nandini.semstack2327@gmail.com', 'sn9D', 'Editorial Co-Comm', FALSE, FALSE),
  ('Krisha Bharwada', 'bharwadakrisha298@gmail.com', 'XnJq', 'Editorial Co-Comm', FALSE, FALSE),
  ('Saee Bachute', 'saee10.b@gmail.com', '261W', 'Editorial Co-Comm', FALSE, FALSE),
  ('Khushi Parekh', 'parekhkhushi013@gmail.com', 't4FV', 'Events Co-Comm', TRUE, FALSE),
  ('Atharva Sawant', 'atharvasawant246@gmail.com', 'w40M', 'Events Co-Comm', FALSE, FALSE),
  ('Krish Sorathia', 'krishsorathia99@gmail.com', 'YDIi', 'Events Co-Comm', FALSE, FALSE),
  ('Jainam Shah', 'jainamshah2425@gmail.com', 'SAu1', 'Events Co-Comm', TRUE, FALSE),
  ('Bhargavi Naik', 'naikbhagu2005@gmail.com', 'trcG', 'Events Co-Comm', FALSE, FALSE),
  ('Vraj sutariya', 'vrajsutariya454@gmail.com', 'nLfW', 'Events Co-Comm', FALSE, FALSE),
  ('Diya Rughani', 'diyarughani@gmail.com', 'Sn1i', 'Events Co-Comm', FALSE, FALSE),
  ('Niharika Veer', 'niharikaveer4@gmail.com', 'Z1wk', 'Events Co-Comm', FALSE, FALSE),
  ('Yash  Thakkar', 'yaash2704@gmail.com', 'KWAN', 'Logistics Co-Comm', FALSE, FALSE),
  ('Rudra Sheth', 'rudrasheth2201@gmail.com', 'QtiE', 'Logistics Co-Comm', FALSE, FALSE),
  ('Sarthak Meher', 'sarthakmeher1083@gmail.com', 'SSEi', 'Logistics Co-Comm', FALSE, FALSE),
  ('Moksh Shah', 'mokshshah25112005@gmail.com', 'aY7m', 'Logistics Co-Comm', FALSE, FALSE),
  ('Shubh Shah', 'shubhshah453@gmail.com', 'Z9dp', 'Logistics Co-Comm', FALSE, FALSE),
  ('Jay Dalvi', 'jaysdalvi05@gmail.com', 'y42G', 'Logistics Co-Comm', FALSE, FALSE),
  ('Sneh Shrimankar', 'snehshrimankar2005@gmail.com', 'D3Pk', 'Logistics Co-Comm', FALSE, FALSE),
  ('Deep Bendale', 'deepbendale69@gmail.com', 'nWso', 'Marketing Co-Comm', FALSE, FALSE),
  ('Gargee Sowani', 'gargeesowani@gmail.com', 'uR54', 'Marketing Co-Comm', TRUE, FALSE),
  ('Pranav Dharwadkar', 'pranav.djsce24@gmail.com', 'HVdR', 'Marketing Co-Comm', FALSE, FALSE),
  ('aaryan joshi', 'aaryanjoshi306@gmail.com', 'VYGp', 'marketing Co-Comm', FALSE, FALSE),
  ('Prathamesh Dattani', 'prathameshdattani.an00174@gmail.com', '1qot', 'Marketing Co-Comm', FALSE, FALSE),
  ('zainab hotelwala', 'zainy3710@gmail.com', 'K2jG', 'marketing Co-Comm', FALSE, FALSE),
  ('Advait Khatu', 'khatuadvait7@gmail.com', 'kogD', 'Marketing Co-Comm', FALSE, FALSE),
  ('Yug Mora', 'mora.yug1125@gmail.com', 'JFRf', 'Marketing Co-Comm', FALSE, FALSE),
  ('Ruchi Gadgil', 'ruchigadgil@gmail.com', 'u7gv', 'Marketing Co-Comm', FALSE, FALSE),
  ('Mihir patil', 'mihirpatil2505@gmail.com', '7R6D', 'Publicity Co-Comm', FALSE, FALSE),
  ('Aniket Prasad', 'akpaniket12@gmail.com', 'cuiv', 'Publicity Co-Comm', FALSE, FALSE),
  ('Koyna Karmakar', 'karmakarkoyna2006@gmail.com', 'qp4j', 'Publicity Co-Comm', FALSE, FALSE),
  ('Niranjan Raina', 'niranjanraina05@gmail.com', 'ZZXN', 'Publicity Co-Comm', FALSE, FALSE),
  ('Dhvani Bhanushali', 'dhvanibhanushali999@gmail.com', 'AZzO', 'Publicity Co-Comm', FALSE, FALSE),
  ('Kristina Pujary', 'kristina.pujary06@gmail.com', 'uqLP', 'Publicity Co-Comm', TRUE, FALSE),
  ('vanshita shah', 'vanshitashah848@gmail.com', 'hFWW', 'pubs Co-Comm', FALSE, FALSE),
  ('Jainam Barbhaya', 'jainambarbhaya1509@gmail.com', 'yfcW', 'Technical Co-Comm', FALSE, FALSE),
  ('Vedehi Choudhary', 'vedehic@gmail.com', '7Shd', 'Technical Co-Comm', FALSE, FALSE)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name,
    password = EXCLUDED.password,
    position = EXCLUDED.position,
    edit_access = EXCLUDED.edit_access,
    view_result_access = EXCLUDED.view_result_access;

-- 4) admin_checkpoints
WITH src(admin_email, checkpoint_real_name, status) AS (
  VALUES
  ('shah.priyansh04@gmail.com', 'registration', TRUE),
  ('shah.priyansh04@gmail.com', 'lunch-day1', FALSE),
  ('shah.priyansh04@gmail.com', 'evening_snacks-day1', TRUE),
  ('shah.priyansh04@gmail.com', 'dinner-day1', FALSE),
  ('shah.priyansh04@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('shah.priyansh04@gmail.com', 'breakfast-day2', FALSE),
  ('harshilshah0504@gmail.com', 'registration', FALSE),
  ('harshilshah0504@gmail.com', 'lunch-day1', FALSE),
  ('harshilshah0504@gmail.com', 'evening_snacks-day1', FALSE),
  ('harshilshah0504@gmail.com', 'dinner-day1', FALSE),
  ('harshilshah0504@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('harshilshah0504@gmail.com', 'breakfast-day2', FALSE),
  ('seanrumao321@gmail.com', 'registration', FALSE),
  ('seanrumao321@gmail.com', 'lunch-day1', FALSE),
  ('seanrumao321@gmail.com', 'evening_snacks-day1', FALSE),
  ('seanrumao321@gmail.com', 'dinner-day1', FALSE),
  ('seanrumao321@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('seanrumao321@gmail.com', 'breakfast-day2', FALSE),
  ('lodhameetr@gmail.com', 'registration', FALSE),
  ('lodhameetr@gmail.com', 'lunch-day1', FALSE),
  ('lodhameetr@gmail.com', 'evening_snacks-day1', FALSE),
  ('lodhameetr@gmail.com', 'dinner-day1', FALSE),
  ('lodhameetr@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('lodhameetr@gmail.com', 'breakfast-day2', FALSE),
  ('dharmilparekh1511@gmail.com', 'registration', TRUE),
  ('dharmilparekh1511@gmail.com', 'lunch-day1', FALSE),
  ('dharmilparekh1511@gmail.com', 'evening_snacks-day1', FALSE),
  ('dharmilparekh1511@gmail.com', 'dinner-day1', FALSE),
  ('dharmilparekh1511@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('dharmilparekh1511@gmail.com', 'breakfast-day2', FALSE),
  ('anvayasolanki@gmail.com', 'registration', FALSE),
  ('anvayasolanki@gmail.com', 'lunch-day1', FALSE),
  ('anvayasolanki@gmail.com', 'evening_snacks-day1', FALSE),
  ('anvayasolanki@gmail.com', 'dinner-day1', FALSE),
  ('anvayasolanki@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('anvayasolanki@gmail.com', 'breakfast-day2', FALSE),
  ('patelmahek1394@gmail.com', 'registration', FALSE),
  ('patelmahek1394@gmail.com', 'lunch-day1', FALSE),
  ('patelmahek1394@gmail.com', 'evening_snacks-day1', FALSE),
  ('patelmahek1394@gmail.com', 'dinner-day1', FALSE),
  ('patelmahek1394@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('patelmahek1394@gmail.com', 'breakfast-day2', FALSE),
  ('lakshyaj690@gmail.com', 'registration', FALSE),
  ('lakshyaj690@gmail.com', 'lunch-day1', FALSE),
  ('lakshyaj690@gmail.com', 'evening_snacks-day1', FALSE),
  ('lakshyaj690@gmail.com', 'dinner-day1', FALSE),
  ('lakshyaj690@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('lakshyaj690@gmail.com', 'breakfast-day2', FALSE),
  ('divamsanghvi@gmail.com', 'registration', FALSE),
  ('divamsanghvi@gmail.com', 'lunch-day1', FALSE),
  ('divamsanghvi@gmail.com', 'evening_snacks-day1', FALSE),
  ('divamsanghvi@gmail.com', 'dinner-day1', FALSE),
  ('divamsanghvi@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('divamsanghvi@gmail.com', 'breakfast-day2', FALSE),
  ('divechamaithili@gmail.com', 'registration', FALSE),
  ('divechamaithili@gmail.com', 'lunch-day1', FALSE),
  ('divechamaithili@gmail.com', 'evening_snacks-day1', FALSE),
  ('divechamaithili@gmail.com', 'dinner-day1', FALSE),
  ('divechamaithili@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('divechamaithili@gmail.com', 'breakfast-day2', FALSE),
  ('ayush.up105@gmail.com', 'registration', FALSE),
  ('ayush.up105@gmail.com', 'lunch-day1', FALSE),
  ('ayush.up105@gmail.com', 'evening_snacks-day1', FALSE),
  ('ayush.up105@gmail.com', 'dinner-day1', FALSE),
  ('ayush.up105@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('ayush.up105@gmail.com', 'breakfast-day2', FALSE),
  ('srinathreddy239@gmail.com', 'registration', TRUE),
  ('srinathreddy239@gmail.com', 'lunch-day1', TRUE),
  ('srinathreddy239@gmail.com', 'evening_snacks-day1', FALSE),
  ('srinathreddy239@gmail.com', 'dinner-day1', FALSE),
  ('srinathreddy239@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('srinathreddy239@gmail.com', 'breakfast-day2', FALSE),
  ('dhvanishah140304@gmail.com', 'registration', FALSE),
  ('dhvanishah140304@gmail.com', 'lunch-day1', FALSE),
  ('dhvanishah140304@gmail.com', 'evening_snacks-day1', FALSE),
  ('dhvanishah140304@gmail.com', 'dinner-day1', FALSE),
  ('dhvanishah140304@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('dhvanishah140304@gmail.com', 'breakfast-day2', FALSE),
  ('yashmadhani2810@gmail.com', 'registration', FALSE),
  ('yashmadhani2810@gmail.com', 'lunch-day1', FALSE),
  ('yashmadhani2810@gmail.com', 'evening_snacks-day1', FALSE),
  ('yashmadhani2810@gmail.com', 'dinner-day1', FALSE),
  ('yashmadhani2810@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('yashmadhani2810@gmail.com', 'breakfast-day2', FALSE),
  ('mohammedparkar68@gmail.com', 'registration', FALSE),
  ('mohammedparkar68@gmail.com', 'lunch-day1', FALSE),
  ('mohammedparkar68@gmail.com', 'evening_snacks-day1', FALSE),
  ('mohammedparkar68@gmail.com', 'dinner-day1', FALSE),
  ('mohammedparkar68@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mohammedparkar68@gmail.com', 'breakfast-day2', FALSE),
  ('nivibokadia@gmail.com', 'registration', FALSE),
  ('nivibokadia@gmail.com', 'lunch-day1', FALSE),
  ('nivibokadia@gmail.com', 'evening_snacks-day1', FALSE),
  ('nivibokadia@gmail.com', 'dinner-day1', FALSE),
  ('nivibokadia@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('nivibokadia@gmail.com', 'breakfast-day2', FALSE),
  ('ashishsatavase13@gmail.com', 'registration', FALSE),
  ('ashishsatavase13@gmail.com', 'lunch-day1', FALSE),
  ('ashishsatavase13@gmail.com', 'evening_snacks-day1', FALSE),
  ('ashishsatavase13@gmail.com', 'dinner-day1', FALSE),
  ('ashishsatavase13@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('ashishsatavase13@gmail.com', 'breakfast-day2', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'registration', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'lunch-day1', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'evening_snacks-day1', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'dinner-day1', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('maheshwarikanishk2005@gmail.com', 'breakfast-day2', FALSE),
  ('kaivanshah292@gmail.com', 'registration', FALSE),
  ('kaivanshah292@gmail.com', 'lunch-day1', FALSE),
  ('kaivanshah292@gmail.com', 'evening_snacks-day1', FALSE),
  ('kaivanshah292@gmail.com', 'dinner-day1', FALSE),
  ('kaivanshah292@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('kaivanshah292@gmail.com', 'breakfast-day2', FALSE),
  ('nitikanitinjain@gmail.com', 'registration', FALSE),
  ('nitikanitinjain@gmail.com', 'lunch-day1', FALSE),
  ('nitikanitinjain@gmail.com', 'evening_snacks-day1', FALSE),
  ('nitikanitinjain@gmail.com', 'dinner-day1', FALSE),
  ('nitikanitinjain@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('nitikanitinjain@gmail.com', 'breakfast-day2', FALSE),
  ('mitulshah8104@gmail.com', 'registration', FALSE),
  ('mitulshah8104@gmail.com', 'lunch-day1', FALSE),
  ('mitulshah8104@gmail.com', 'evening_snacks-day1', FALSE),
  ('mitulshah8104@gmail.com', 'dinner-day1', FALSE),
  ('mitulshah8104@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mitulshah8104@gmail.com', 'breakfast-day2', FALSE),
  ('yash240904@gmail.com', 'registration', FALSE),
  ('yash240904@gmail.com', 'lunch-day1', FALSE),
  ('yash240904@gmail.com', 'evening_snacks-day1', FALSE),
  ('yash240904@gmail.com', 'dinner-day1', FALSE),
  ('yash240904@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('yash240904@gmail.com', 'breakfast-day2', FALSE),
  ('dikshantbadawadagi@gmail.com', 'registration', FALSE),
  ('dikshantbadawadagi@gmail.com', 'lunch-day1', FALSE),
  ('dikshantbadawadagi@gmail.com', 'evening_snacks-day1', FALSE),
  ('dikshantbadawadagi@gmail.com', 'dinner-day1', FALSE),
  ('dikshantbadawadagi@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('dikshantbadawadagi@gmail.com', 'breakfast-day2', FALSE),
  ('taksh1816@gmail.com', 'registration', FALSE),
  ('taksh1816@gmail.com', 'lunch-day1', FALSE),
  ('taksh1816@gmail.com', 'evening_snacks-day1', FALSE),
  ('taksh1816@gmail.com', 'dinner-day1', FALSE),
  ('taksh1816@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('taksh1816@gmail.com', 'breakfast-day2', FALSE),
  ('rishibpanchal006@gmail.com', 'registration', TRUE),
  ('rishibpanchal006@gmail.com', 'lunch-day1', FALSE),
  ('rishibpanchal006@gmail.com', 'evening_snacks-day1', TRUE),
  ('rishibpanchal006@gmail.com', 'dinner-day1', FALSE),
  ('rishibpanchal006@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('rishibpanchal006@gmail.com', 'breakfast-day2', FALSE),
  ('waghelahiren16@gmail.com', 'registration', TRUE),
  ('waghelahiren16@gmail.com', 'lunch-day1', FALSE),
  ('waghelahiren16@gmail.com', 'evening_snacks-day1', TRUE),
  ('waghelahiren16@gmail.com', 'dinner-day1', FALSE),
  ('waghelahiren16@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('waghelahiren16@gmail.com', 'breakfast-day2', FALSE),
  ('rachitchotalia99@gmail.com', 'registration', TRUE),
  ('rachitchotalia99@gmail.com', 'lunch-day1', FALSE),
  ('rachitchotalia99@gmail.com', 'evening_snacks-day1', TRUE),
  ('rachitchotalia99@gmail.com', 'dinner-day1', FALSE),
  ('rachitchotalia99@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('rachitchotalia99@gmail.com', 'breakfast-day2', FALSE),
  ('aaryanhkhanna@gmail.com', 'registration', TRUE),
  ('aaryanhkhanna@gmail.com', 'lunch-day1', FALSE),
  ('aaryanhkhanna@gmail.com', 'evening_snacks-day1', FALSE),
  ('aaryanhkhanna@gmail.com', 'dinner-day1', FALSE),
  ('aaryanhkhanna@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('aaryanhkhanna@gmail.com', 'breakfast-day2', FALSE),
  ('mananshahstudios1@gmail.com', 'registration', FALSE),
  ('mananshahstudios1@gmail.com', 'lunch-day1', FALSE),
  ('mananshahstudios1@gmail.com', 'evening_snacks-day1', TRUE),
  ('mananshahstudios1@gmail.com', 'dinner-day1', FALSE),
  ('mananshahstudios1@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mananshahstudios1@gmail.com', 'breakfast-day2', FALSE),
  ('diyakpanchal0405@gmail.com', 'registration', FALSE),
  ('diyakpanchal0405@gmail.com', 'lunch-day1', FALSE),
  ('diyakpanchal0405@gmail.com', 'evening_snacks-day1', FALSE),
  ('diyakpanchal0405@gmail.com', 'dinner-day1', FALSE),
  ('diyakpanchal0405@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('diyakpanchal0405@gmail.com', 'breakfast-day2', FALSE),
  ('doshiarpit2005@gmail.com', 'registration', TRUE),
  ('doshiarpit2005@gmail.com', 'lunch-day1', FALSE),
  ('doshiarpit2005@gmail.com', 'evening_snacks-day1', FALSE),
  ('doshiarpit2005@gmail.com', 'dinner-day1', FALSE),
  ('doshiarpit2005@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('doshiarpit2005@gmail.com', 'breakfast-day2', FALSE),
  ('yashvi.h.mehta235@gmail.com', 'registration', FALSE),
  ('yashvi.h.mehta235@gmail.com', 'lunch-day1', FALSE),
  ('yashvi.h.mehta235@gmail.com', 'evening_snacks-day1', TRUE),
  ('yashvi.h.mehta235@gmail.com', 'dinner-day1', FALSE),
  ('yashvi.h.mehta235@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('yashvi.h.mehta235@gmail.com', 'breakfast-day2', FALSE),
  ('tanvikamath22@gmail.com', 'registration', TRUE),
  ('tanvikamath22@gmail.com', 'lunch-day1', FALSE),
  ('tanvikamath22@gmail.com', 'evening_snacks-day1', FALSE),
  ('tanvikamath22@gmail.com', 'dinner-day1', FALSE),
  ('tanvikamath22@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('tanvikamath22@gmail.com', 'breakfast-day2', FALSE),
  ('pranavagarwal2073@gmail.com', 'registration', TRUE),
  ('pranavagarwal2073@gmail.com', 'lunch-day1', FALSE),
  ('pranavagarwal2073@gmail.com', 'evening_snacks-day1', TRUE),
  ('pranavagarwal2073@gmail.com', 'dinner-day1', FALSE),
  ('pranavagarwal2073@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('pranavagarwal2073@gmail.com', 'breakfast-day2', FALSE),
  ('nandini.semstack2327@gmail.com', 'registration', TRUE),
  ('nandini.semstack2327@gmail.com', 'lunch-day1', FALSE),
  ('nandini.semstack2327@gmail.com', 'evening_snacks-day1', TRUE),
  ('nandini.semstack2327@gmail.com', 'dinner-day1', FALSE),
  ('nandini.semstack2327@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('nandini.semstack2327@gmail.com', 'breakfast-day2', FALSE),
  ('bharwadakrisha298@gmail.com', 'registration', FALSE),
  ('bharwadakrisha298@gmail.com', 'lunch-day1', FALSE),
  ('bharwadakrisha298@gmail.com', 'evening_snacks-day1', FALSE),
  ('bharwadakrisha298@gmail.com', 'dinner-day1', FALSE),
  ('bharwadakrisha298@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('bharwadakrisha298@gmail.com', 'breakfast-day2', FALSE),
  ('saee10.b@gmail.com', 'registration', TRUE),
  ('saee10.b@gmail.com', 'lunch-day1', FALSE),
  ('saee10.b@gmail.com', 'evening_snacks-day1', FALSE),
  ('saee10.b@gmail.com', 'dinner-day1', FALSE),
  ('saee10.b@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('saee10.b@gmail.com', 'breakfast-day2', FALSE),
  ('parekhkhushi013@gmail.com', 'registration', FALSE),
  ('parekhkhushi013@gmail.com', 'lunch-day1', FALSE),
  ('parekhkhushi013@gmail.com', 'evening_snacks-day1', TRUE),
  ('parekhkhushi013@gmail.com', 'dinner-day1', FALSE),
  ('parekhkhushi013@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('parekhkhushi013@gmail.com', 'breakfast-day2', FALSE),
  ('atharvasawant246@gmail.com', 'registration', FALSE),
  ('atharvasawant246@gmail.com', 'lunch-day1', FALSE),
  ('atharvasawant246@gmail.com', 'evening_snacks-day1', FALSE),
  ('atharvasawant246@gmail.com', 'dinner-day1', FALSE),
  ('atharvasawant246@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('atharvasawant246@gmail.com', 'breakfast-day2', FALSE),
  ('krishsorathia99@gmail.com', 'registration', FALSE),
  ('krishsorathia99@gmail.com', 'lunch-day1', FALSE),
  ('krishsorathia99@gmail.com', 'evening_snacks-day1', FALSE),
  ('krishsorathia99@gmail.com', 'dinner-day1', FALSE),
  ('krishsorathia99@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('krishsorathia99@gmail.com', 'breakfast-day2', FALSE),
  ('jainamshah2425@gmail.com', 'registration', TRUE),
  ('jainamshah2425@gmail.com', 'lunch-day1', FALSE),
  ('jainamshah2425@gmail.com', 'evening_snacks-day1', FALSE),
  ('jainamshah2425@gmail.com', 'dinner-day1', FALSE),
  ('jainamshah2425@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('jainamshah2425@gmail.com', 'breakfast-day2', FALSE),
  ('naikbhagu2005@gmail.com', 'registration', FALSE),
  ('naikbhagu2005@gmail.com', 'lunch-day1', FALSE),
  ('naikbhagu2005@gmail.com', 'evening_snacks-day1', FALSE),
  ('naikbhagu2005@gmail.com', 'dinner-day1', FALSE),
  ('naikbhagu2005@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('naikbhagu2005@gmail.com', 'breakfast-day2', FALSE),
  ('vrajsutariya454@gmail.com', 'registration', FALSE),
  ('vrajsutariya454@gmail.com', 'lunch-day1', FALSE),
  ('vrajsutariya454@gmail.com', 'evening_snacks-day1', FALSE),
  ('vrajsutariya454@gmail.com', 'dinner-day1', FALSE),
  ('vrajsutariya454@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('vrajsutariya454@gmail.com', 'breakfast-day2', FALSE),
  ('diyarughani@gmail.com', 'registration', TRUE),
  ('diyarughani@gmail.com', 'lunch-day1', FALSE),
  ('diyarughani@gmail.com', 'evening_snacks-day1', TRUE),
  ('diyarughani@gmail.com', 'dinner-day1', FALSE),
  ('diyarughani@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('diyarughani@gmail.com', 'breakfast-day2', FALSE),
  ('niharikaveer4@gmail.com', 'registration', TRUE),
  ('niharikaveer4@gmail.com', 'lunch-day1', FALSE),
  ('niharikaveer4@gmail.com', 'evening_snacks-day1', TRUE),
  ('niharikaveer4@gmail.com', 'dinner-day1', FALSE),
  ('niharikaveer4@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('niharikaveer4@gmail.com', 'breakfast-day2', FALSE),
  ('yaash2704@gmail.com', 'registration', TRUE),
  ('yaash2704@gmail.com', 'lunch-day1', FALSE),
  ('yaash2704@gmail.com', 'evening_snacks-day1', TRUE),
  ('yaash2704@gmail.com', 'dinner-day1', FALSE),
  ('yaash2704@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('yaash2704@gmail.com', 'breakfast-day2', FALSE),
  ('rudrasheth2201@gmail.com', 'registration', TRUE),
  ('rudrasheth2201@gmail.com', 'lunch-day1', FALSE),
  ('rudrasheth2201@gmail.com', 'evening_snacks-day1', TRUE),
  ('rudrasheth2201@gmail.com', 'dinner-day1', FALSE),
  ('rudrasheth2201@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('rudrasheth2201@gmail.com', 'breakfast-day2', FALSE),
  ('sarthakmeher1083@gmail.com', 'registration', FALSE),
  ('sarthakmeher1083@gmail.com', 'lunch-day1', FALSE),
  ('sarthakmeher1083@gmail.com', 'evening_snacks-day1', FALSE),
  ('sarthakmeher1083@gmail.com', 'dinner-day1', FALSE),
  ('sarthakmeher1083@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('sarthakmeher1083@gmail.com', 'breakfast-day2', FALSE),
  ('mokshshah25112005@gmail.com', 'registration', TRUE),
  ('mokshshah25112005@gmail.com', 'lunch-day1', FALSE),
  ('mokshshah25112005@gmail.com', 'evening_snacks-day1', FALSE),
  ('mokshshah25112005@gmail.com', 'dinner-day1', FALSE),
  ('mokshshah25112005@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mokshshah25112005@gmail.com', 'breakfast-day2', FALSE),
  ('shubhshah453@gmail.com', 'registration', TRUE),
  ('shubhshah453@gmail.com', 'lunch-day1', FALSE),
  ('shubhshah453@gmail.com', 'evening_snacks-day1', TRUE),
  ('shubhshah453@gmail.com', 'dinner-day1', FALSE),
  ('shubhshah453@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('shubhshah453@gmail.com', 'breakfast-day2', FALSE),
  ('jaysdalvi05@gmail.com', 'registration', TRUE),
  ('jaysdalvi05@gmail.com', 'lunch-day1', FALSE),
  ('jaysdalvi05@gmail.com', 'evening_snacks-day1', TRUE),
  ('jaysdalvi05@gmail.com', 'dinner-day1', FALSE),
  ('jaysdalvi05@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('jaysdalvi05@gmail.com', 'breakfast-day2', FALSE),
  ('snehshrimankar2005@gmail.com', 'registration', TRUE),
  ('snehshrimankar2005@gmail.com', 'lunch-day1', FALSE),
  ('snehshrimankar2005@gmail.com', 'evening_snacks-day1', TRUE),
  ('snehshrimankar2005@gmail.com', 'dinner-day1', FALSE),
  ('snehshrimankar2005@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('snehshrimankar2005@gmail.com', 'breakfast-day2', FALSE),
  ('deepbendale69@gmail.com', 'registration', FALSE),
  ('deepbendale69@gmail.com', 'lunch-day1', FALSE),
  ('deepbendale69@gmail.com', 'evening_snacks-day1', FALSE),
  ('deepbendale69@gmail.com', 'dinner-day1', FALSE),
  ('deepbendale69@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('deepbendale69@gmail.com', 'breakfast-day2', FALSE),
  ('gargeesowani@gmail.com', 'registration', FALSE),
  ('gargeesowani@gmail.com', 'lunch-day1', FALSE),
  ('gargeesowani@gmail.com', 'evening_snacks-day1', FALSE),
  ('gargeesowani@gmail.com', 'dinner-day1', FALSE),
  ('gargeesowani@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('gargeesowani@gmail.com', 'breakfast-day2', FALSE),
  ('pranav.djsce24@gmail.com', 'registration', FALSE),
  ('pranav.djsce24@gmail.com', 'lunch-day1', FALSE),
  ('pranav.djsce24@gmail.com', 'evening_snacks-day1', FALSE),
  ('pranav.djsce24@gmail.com', 'dinner-day1', FALSE),
  ('pranav.djsce24@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('pranav.djsce24@gmail.com', 'breakfast-day2', FALSE),
  ('aaryanjoshi306@gmail.com', 'registration', FALSE),
  ('aaryanjoshi306@gmail.com', 'lunch-day1', FALSE),
  ('aaryanjoshi306@gmail.com', 'evening_snacks-day1', TRUE),
  ('aaryanjoshi306@gmail.com', 'dinner-day1', FALSE),
  ('aaryanjoshi306@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('aaryanjoshi306@gmail.com', 'breakfast-day2', FALSE),
  ('prathameshdattani.an00174@gmail.com', 'registration', TRUE),
  ('prathameshdattani.an00174@gmail.com', 'lunch-day1', FALSE),
  ('prathameshdattani.an00174@gmail.com', 'evening_snacks-day1', TRUE),
  ('prathameshdattani.an00174@gmail.com', 'dinner-day1', FALSE),
  ('prathameshdattani.an00174@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('prathameshdattani.an00174@gmail.com', 'breakfast-day2', FALSE),
  ('zainy3710@gmail.com', 'registration', TRUE),
  ('zainy3710@gmail.com', 'lunch-day1', FALSE),
  ('zainy3710@gmail.com', 'evening_snacks-day1', TRUE),
  ('zainy3710@gmail.com', 'dinner-day1', FALSE),
  ('zainy3710@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('zainy3710@gmail.com', 'breakfast-day2', FALSE),
  ('khatuadvait7@gmail.com', 'registration', TRUE),
  ('khatuadvait7@gmail.com', 'lunch-day1', FALSE),
  ('khatuadvait7@gmail.com', 'evening_snacks-day1', TRUE),
  ('khatuadvait7@gmail.com', 'dinner-day1', FALSE),
  ('khatuadvait7@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('khatuadvait7@gmail.com', 'breakfast-day2', FALSE),
  ('mora.yug1125@gmail.com', 'registration', TRUE),
  ('mora.yug1125@gmail.com', 'lunch-day1', FALSE),
  ('mora.yug1125@gmail.com', 'evening_snacks-day1', FALSE),
  ('mora.yug1125@gmail.com', 'dinner-day1', FALSE),
  ('mora.yug1125@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mora.yug1125@gmail.com', 'breakfast-day2', FALSE),
  ('ruchigadgil@gmail.com', 'registration', FALSE),
  ('ruchigadgil@gmail.com', 'lunch-day1', FALSE),
  ('ruchigadgil@gmail.com', 'evening_snacks-day1', FALSE),
  ('ruchigadgil@gmail.com', 'dinner-day1', FALSE),
  ('ruchigadgil@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('ruchigadgil@gmail.com', 'breakfast-day2', FALSE),
  ('mihirpatil2505@gmail.com', 'registration', TRUE),
  ('mihirpatil2505@gmail.com', 'lunch-day1', FALSE),
  ('mihirpatil2505@gmail.com', 'evening_snacks-day1', FALSE),
  ('mihirpatil2505@gmail.com', 'dinner-day1', FALSE),
  ('mihirpatil2505@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('mihirpatil2505@gmail.com', 'breakfast-day2', FALSE),
  ('akpaniket12@gmail.com', 'registration', FALSE),
  ('akpaniket12@gmail.com', 'lunch-day1', FALSE),
  ('akpaniket12@gmail.com', 'evening_snacks-day1', FALSE),
  ('akpaniket12@gmail.com', 'dinner-day1', FALSE),
  ('akpaniket12@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('akpaniket12@gmail.com', 'breakfast-day2', FALSE),
  ('karmakarkoyna2006@gmail.com', 'registration', TRUE),
  ('karmakarkoyna2006@gmail.com', 'lunch-day1', FALSE),
  ('karmakarkoyna2006@gmail.com', 'evening_snacks-day1', TRUE),
  ('karmakarkoyna2006@gmail.com', 'dinner-day1', FALSE),
  ('karmakarkoyna2006@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('karmakarkoyna2006@gmail.com', 'breakfast-day2', FALSE),
  ('niranjanraina05@gmail.com', 'registration', FALSE),
  ('niranjanraina05@gmail.com', 'lunch-day1', FALSE),
  ('niranjanraina05@gmail.com', 'evening_snacks-day1', FALSE),
  ('niranjanraina05@gmail.com', 'dinner-day1', FALSE),
  ('niranjanraina05@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('niranjanraina05@gmail.com', 'breakfast-day2', FALSE),
  ('dhvanibhanushali999@gmail.com', 'registration', TRUE),
  ('dhvanibhanushali999@gmail.com', 'lunch-day1', FALSE),
  ('dhvanibhanushali999@gmail.com', 'evening_snacks-day1', FALSE),
  ('dhvanibhanushali999@gmail.com', 'dinner-day1', FALSE),
  ('dhvanibhanushali999@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('dhvanibhanushali999@gmail.com', 'breakfast-day2', FALSE),
  ('kristina.pujary06@gmail.com', 'registration', FALSE),
  ('kristina.pujary06@gmail.com', 'lunch-day1', FALSE),
  ('kristina.pujary06@gmail.com', 'evening_snacks-day1', FALSE),
  ('kristina.pujary06@gmail.com', 'dinner-day1', FALSE),
  ('kristina.pujary06@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('kristina.pujary06@gmail.com', 'breakfast-day2', FALSE),
  ('vanshitashah848@gmail.com', 'registration', TRUE),
  ('vanshitashah848@gmail.com', 'lunch-day1', FALSE),
  ('vanshitashah848@gmail.com', 'evening_snacks-day1', FALSE),
  ('vanshitashah848@gmail.com', 'dinner-day1', FALSE),
  ('vanshitashah848@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('vanshitashah848@gmail.com', 'breakfast-day2', FALSE),
  ('jainambarbhaya1509@gmail.com', 'registration', FALSE),
  ('jainambarbhaya1509@gmail.com', 'lunch-day1', FALSE),
  ('jainambarbhaya1509@gmail.com', 'evening_snacks-day1', FALSE),
  ('jainambarbhaya1509@gmail.com', 'dinner-day1', FALSE),
  ('jainambarbhaya1509@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('jainambarbhaya1509@gmail.com', 'breakfast-day2', FALSE),
  ('vedehic@gmail.com', 'registration', TRUE),
  ('vedehic@gmail.com', 'lunch-day1', FALSE),
  ('vedehic@gmail.com', 'evening_snacks-day1', TRUE),
  ('vedehic@gmail.com', 'dinner-day1', FALSE),
  ('vedehic@gmail.com', 'midnight_refreshments-day1', FALSE),
  ('vedehic@gmail.com', 'breakfast-day2', FALSE)
), mapped AS (
  SELECT a.id AS admin_id, c.id AS checkpoint_id, src.status
  FROM src
  JOIN admins a ON btrim(lower(a.email)) = btrim(lower(src.admin_email))
  JOIN checkpoints c ON c.checkpoint_real_name = src.checkpoint_real_name
)
INSERT INTO admin_checkpoints (admin_id, checkpoint_id, status)
SELECT m.admin_id, m.checkpoint_id, m.status
FROM mapped m
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_checkpoints ac
  WHERE ac.admin_id = m.admin_id
    AND ac.checkpoint_id = m.checkpoint_id
);

-- 5) global_settings
INSERT INTO global_settings (button_visibility)
VALUES (FALSE);

-- 6) judges
INSERT INTO judges (name, email, password, description, ps_no, ps_title, next_round_top_count, round1_finished, round2_finished)
VALUES
  ('Kunal Shah', 'kunal.Shah@realvision.com', 'zVwA', 'I am ps 1', 1, 'Web', 2, FALSE, TRUE),
  ('Sagar Doshi', 'sagar@dextralabs.com', 'qXw1', 'I am ps 2', 2, 'App', 2, TRUE, TRUE),
  ('Mahendra', 'mahendra@projectx38.com', 'EpW4', 'I am ps 3', 3, 'AI/ML', 2, TRUE, TRUE),
  ('Vijay Agarwal', 'vijay@dextralabs.com', 'S485', 'I am ps 4', 4, 'AI/ML', 2, TRUE, TRUE),
  ('Shounak Shetty', 'shounak.shetty@brinc.io', 'PmAq', 'I am ps 5', 5, 'Blockchain', 2, TRUE, TRUE),
  ('Atharva Wagh', 'wagh.atharva14@gmail.com', 'w0Ds', 'I am ps 6', 6, 'Open Innovation', 2, TRUE, TRUE)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name,
    password = EXCLUDED.password,
    description = EXCLUDED.description,
    ps_no = EXCLUDED.ps_no,
    ps_title = EXCLUDED.ps_title,
    next_round_top_count = EXCLUDED.next_round_top_count,
    round1_finished = EXCLUDED.round1_finished,
    round2_finished = EXCLUDED.round2_finished;

-- 7) teams
INSERT INTO teams (team_code, team_name)
VALUES
  ('C001', 'Tabs_Not_Spaces'),
  ('C003', 'Tech Titans'),
  ('C004', 'ChennaiExpress'),
  ('C005', 'Ethereal Elites'),
  ('C007', 'K-Means Killers'),
  ('C008', 'All Stackers'),
  ('C009', 'Ninjas in Paris'),
  ('C010', 'Bogan_Breakers'),
  ('C011', 'Tech a Byte'),
  ('C012', 'Mango DB'),
  ('C013', 'CTRL-ALT-ELITE'),
  ('C014', 'Innovative Minds'),
  ('C015', 'EnigmaCode'),
  ('C016', 'ByteByByte'),
  ('C017', 'Debug Thugs'),
  ('C018', 'Git Commit'),
  ('C019', 'CapsLock'),
  ('C020', 'MishtiDoi'),
  ('C021', 'Ctrl+Alt+Elite'),
  ('C022', 'Phoenix'),
  ('C023', 'Kool Kidz Klub'),
  ('C024', 'Syntax Terror'),
  ('C025', 'brockband'),
  ('C026', 'Byte Brahmand'),
  ('C027', 'Code Omega'),
  ('C029', 'Paypal Mafia'),
  ('C030', 'Serial_Hackers'),
  ('C031', 'SYNERGY'),
  ('C033', 'Tensionflow'),
  ('C035', 'The boys'),
  ('C036', 'BROGRAMMERS'),
  ('C037', 'Akatsuki'),
  ('C038', 'youFools'),
  ('C039', 'Tech Nexus'),
  ('C040', 'ByteMe'),
  ('C041', 'Syndicate'),
  ('C042', 'init 0'),
  ('C043', '2p | !2p'),
  ('C045', 'ReLulu'),
  ('C046', '<Block.sol/>'),
  ('C048', 'Chipi chipi'),
  ('C050', 'AZTG'),
  ('C051', 'CodeRed'),
  ('C052', 'LLMAO'),
  ('C053', 'Metasploit'),
  ('C054', 'Enemies of Syntax'),
  ('C055', 'Code X'),
  ('C056', 'Bit Lords V2'),
  ('C057', 'ITerative bytes'),
  ('C058', 'Soulcoders'),
  ('C060', 'CodeBrewers')
ON CONFLICT (team_code) DO UPDATE
SET team_name = COALESCE(EXCLUDED.team_name, teams.team_name);

-- 8) round_teams
WITH src(judge_email, team_code, round) AS (
  VALUES
  ('kunal.Shah@realvision.com', 'C001', 1),
  ('kunal.Shah@realvision.com', 'C007', 1),
  ('kunal.Shah@realvision.com', 'C011', 1),
  ('kunal.Shah@realvision.com', 'C055', 1),
  ('kunal.Shah@realvision.com', 'C019', 1),
  ('kunal.Shah@realvision.com', 'C025', 1),
  ('kunal.Shah@realvision.com', 'C031', 1),
  ('kunal.Shah@realvision.com', 'C037', 1),
  ('kunal.Shah@realvision.com', 'C043', 1),
  ('kunal.Shah@realvision.com', 'C019', 2),
  ('kunal.Shah@realvision.com', 'C001', 2),
  ('kunal.Shah@realvision.com', 'C056', 2),
  ('kunal.Shah@realvision.com', 'C026', 2),
  ('kunal.Shah@realvision.com', 'C045', 2),
  ('kunal.Shah@realvision.com', 'C009', 2),
  ('kunal.Shah@realvision.com', 'C016', 2),
  ('kunal.Shah@realvision.com', 'C040', 2),
  ('kunal.Shah@realvision.com', 'C023', 2),
  ('kunal.Shah@realvision.com', 'C053', 2),
  ('kunal.Shah@realvision.com', 'C060', 2),
  ('kunal.Shah@realvision.com', 'C054', 2),
  ('sagar@dextralabs.com', 'C012', 1),
  ('sagar@dextralabs.com', 'C008', 1),
  ('sagar@dextralabs.com', 'C020', 1),
  ('sagar@dextralabs.com', 'C026', 1),
  ('sagar@dextralabs.com', 'C038', 1),
  ('sagar@dextralabs.com', 'C050', 1),
  ('sagar@dextralabs.com', 'C056', 1),
  ('sagar@dextralabs.com', 'C019', 2),
  ('sagar@dextralabs.com', 'C001', 2),
  ('sagar@dextralabs.com', 'C056', 2),
  ('sagar@dextralabs.com', 'C026', 2),
  ('sagar@dextralabs.com', 'C045', 2),
  ('sagar@dextralabs.com', 'C009', 2),
  ('sagar@dextralabs.com', 'C016', 2),
  ('sagar@dextralabs.com', 'C040', 2),
  ('sagar@dextralabs.com', 'C023', 2),
  ('sagar@dextralabs.com', 'C053', 2),
  ('sagar@dextralabs.com', 'C060', 2),
  ('sagar@dextralabs.com', 'C054', 2),
  ('mahendra@projectx38.com', 'C003', 1),
  ('mahendra@projectx38.com', 'C027', 1),
  ('mahendra@projectx38.com', 'C015', 1),
  ('mahendra@projectx38.com', 'C021', 1),
  ('mahendra@projectx38.com', 'C009', 1),
  ('mahendra@projectx38.com', 'C033', 1),
  ('mahendra@projectx38.com', 'C039', 1),
  ('mahendra@projectx38.com', 'C045', 1),
  ('mahendra@projectx38.com', 'C051', 1),
  ('mahendra@projectx38.com', 'C057', 1),
  ('mahendra@projectx38.com', 'C019', 2),
  ('mahendra@projectx38.com', 'C001', 2),
  ('mahendra@projectx38.com', 'C056', 2),
  ('mahendra@projectx38.com', 'C026', 2),
  ('mahendra@projectx38.com', 'C045', 2),
  ('mahendra@projectx38.com', 'C009', 2),
  ('mahendra@projectx38.com', 'C016', 2),
  ('mahendra@projectx38.com', 'C040', 2),
  ('mahendra@projectx38.com', 'C023', 2),
  ('mahendra@projectx38.com', 'C053', 2),
  ('mahendra@projectx38.com', 'C060', 2),
  ('mahendra@projectx38.com', 'C054', 2),
  ('vijay@dextralabs.com', 'C004', 1),
  ('vijay@dextralabs.com', 'C010', 1),
  ('vijay@dextralabs.com', 'C058', 1),
  ('vijay@dextralabs.com', 'C046', 1),
  ('vijay@dextralabs.com', 'C022', 1),
  ('vijay@dextralabs.com', 'C040', 1),
  ('vijay@dextralabs.com', 'C052', 1),
  ('vijay@dextralabs.com', 'C016', 1),
  ('vijay@dextralabs.com', 'C019', 2),
  ('vijay@dextralabs.com', 'C001', 2),
  ('vijay@dextralabs.com', 'C056', 2),
  ('vijay@dextralabs.com', 'C026', 2),
  ('vijay@dextralabs.com', 'C045', 2),
  ('vijay@dextralabs.com', 'C009', 2),
  ('vijay@dextralabs.com', 'C016', 2),
  ('vijay@dextralabs.com', 'C040', 2),
  ('vijay@dextralabs.com', 'C023', 2),
  ('vijay@dextralabs.com', 'C053', 2),
  ('vijay@dextralabs.com', 'C060', 2),
  ('vijay@dextralabs.com', 'C054', 2),
  ('shounak.shetty@brinc.io', 'C005', 1),
  ('shounak.shetty@brinc.io', 'C017', 1),
  ('shounak.shetty@brinc.io', 'C013', 1),
  ('shounak.shetty@brinc.io', 'C041', 1),
  ('shounak.shetty@brinc.io', 'C029', 1),
  ('shounak.shetty@brinc.io', 'C023', 1),
  ('shounak.shetty@brinc.io', 'C035', 1),
  ('shounak.shetty@brinc.io', 'C053', 1),
  ('shounak.shetty@brinc.io', 'C019', 2),
  ('shounak.shetty@brinc.io', 'C001', 2),
  ('shounak.shetty@brinc.io', 'C056', 2),
  ('shounak.shetty@brinc.io', 'C026', 2),
  ('shounak.shetty@brinc.io', 'C045', 2),
  ('shounak.shetty@brinc.io', 'C009', 2),
  ('shounak.shetty@brinc.io', 'C016', 2),
  ('shounak.shetty@brinc.io', 'C040', 2),
  ('shounak.shetty@brinc.io', 'C023', 2),
  ('shounak.shetty@brinc.io', 'C053', 2),
  ('shounak.shetty@brinc.io', 'C060', 2),
  ('shounak.shetty@brinc.io', 'C054', 2),
  ('wagh.atharva14@gmail.com', 'C014', 1),
  ('wagh.atharva14@gmail.com', 'C048', 1),
  ('wagh.atharva14@gmail.com', 'C018', 1),
  ('wagh.atharva14@gmail.com', 'C030', 1),
  ('wagh.atharva14@gmail.com', 'C036', 1),
  ('wagh.atharva14@gmail.com', 'C054', 1),
  ('wagh.atharva14@gmail.com', 'C060', 1),
  ('wagh.atharva14@gmail.com', 'C042', 1),
  ('wagh.atharva14@gmail.com', 'C024', 1),
  ('wagh.atharva14@gmail.com', 'C019', 2),
  ('wagh.atharva14@gmail.com', 'C001', 2),
  ('wagh.atharva14@gmail.com', 'C056', 2),
  ('wagh.atharva14@gmail.com', 'C026', 2),
  ('wagh.atharva14@gmail.com', 'C045', 2),
  ('wagh.atharva14@gmail.com', 'C009', 2),
  ('wagh.atharva14@gmail.com', 'C016', 2),
  ('wagh.atharva14@gmail.com', 'C040', 2),
  ('wagh.atharva14@gmail.com', 'C023', 2),
  ('wagh.atharva14@gmail.com', 'C053', 2),
  ('wagh.atharva14@gmail.com', 'C060', 2),
  ('wagh.atharva14@gmail.com', 'C054', 2)
), mapped AS (
  SELECT j.id AS judge_id, t.id AS team_id, src.round
  FROM src
  JOIN judges j ON btrim(lower(j.email)) = btrim(lower(src.judge_email))
  JOIN teams t ON t.team_code = src.team_code
)
INSERT INTO round_teams (judge_id, team_id, round)
SELECT m.judge_id, m.team_id, m.round
FROM mapped m
WHERE NOT EXISTS (
  SELECT 1
  FROM round_teams rt
  WHERE rt.judge_id = m.judge_id
    AND rt.team_id = m.team_id
    AND rt.round = m.round
);

-- 9) scores
WITH src(judge_email, team_code, round, criterion_name, score) AS (
  VALUES
  ('kunal.Shah@realvision.com', 'C001', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C001', 1, 'Functionality', 6),
  ('kunal.Shah@realvision.com', 'C001', 1, 'Presentation', 7),
  ('kunal.Shah@realvision.com', 'C001', 1, 'Feasibility', 8),
  ('kunal.Shah@realvision.com', 'C001', 1, 'UI/UX', 8),
  ('kunal.Shah@realvision.com', 'C007', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C007', 1, 'Functionality', 7),
  ('kunal.Shah@realvision.com', 'C007', 1, 'Presentation', 7),
  ('kunal.Shah@realvision.com', 'C007', 1, 'Feasibility', 7),
  ('kunal.Shah@realvision.com', 'C007', 1, 'UI/UX', 7),
  ('kunal.Shah@realvision.com', 'C011', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C011', 1, 'Functionality', 7),
  ('kunal.Shah@realvision.com', 'C011', 1, 'Presentation', 6),
  ('kunal.Shah@realvision.com', 'C011', 1, 'Feasibility', 8),
  ('kunal.Shah@realvision.com', 'C011', 1, 'UI/UX', 6),
  ('kunal.Shah@realvision.com', 'C055', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C055', 1, 'Functionality', 6),
  ('kunal.Shah@realvision.com', 'C055', 1, 'Presentation', 7),
  ('kunal.Shah@realvision.com', 'C055', 1, 'Feasibility', 6),
  ('kunal.Shah@realvision.com', 'C055', 1, 'UI/UX', 7),
  ('kunal.Shah@realvision.com', 'C019', 1, 'Innovation', 7),
  ('kunal.Shah@realvision.com', 'C019', 1, 'Functionality', 6),
  ('kunal.Shah@realvision.com', 'C019', 1, 'Presentation', 5),
  ('kunal.Shah@realvision.com', 'C019', 1, 'Feasibility', 8),
  ('kunal.Shah@realvision.com', 'C019', 1, 'UI/UX', 9),
  ('kunal.Shah@realvision.com', 'C025', 1, 'Innovation', 8),
  ('kunal.Shah@realvision.com', 'C025', 1, 'Functionality', 7),
  ('kunal.Shah@realvision.com', 'C025', 1, 'Presentation', 6),
  ('kunal.Shah@realvision.com', 'C025', 1, 'Feasibility', 6),
  ('kunal.Shah@realvision.com', 'C025', 1, 'UI/UX', 8),
  ('kunal.Shah@realvision.com', 'C031', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C031', 1, 'Functionality', 4),
  ('kunal.Shah@realvision.com', 'C031', 1, 'Presentation', 4),
  ('kunal.Shah@realvision.com', 'C031', 1, 'Feasibility', 7),
  ('kunal.Shah@realvision.com', 'C031', 1, 'UI/UX', 6),
  ('kunal.Shah@realvision.com', 'C037', 1, 'Innovation', 6),
  ('kunal.Shah@realvision.com', 'C037', 1, 'Functionality', 5),
  ('kunal.Shah@realvision.com', 'C037', 1, 'Presentation', 5),
  ('kunal.Shah@realvision.com', 'C037', 1, 'Feasibility', 7),
  ('kunal.Shah@realvision.com', 'C037', 1, 'UI/UX', 7),
  ('kunal.Shah@realvision.com', 'C043', 1, 'Innovation', 7),
  ('kunal.Shah@realvision.com', 'C043', 1, 'Functionality', 5),
  ('kunal.Shah@realvision.com', 'C043', 1, 'Presentation', 6),
  ('kunal.Shah@realvision.com', 'C043', 1, 'Feasibility', 6),
  ('kunal.Shah@realvision.com', 'C043', 1, 'UI/UX', 8),
  ('kunal.Shah@realvision.com', 'C019', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C019', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C019', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C019', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C019', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C001', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C001', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C001', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C001', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C001', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C056', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C056', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C056', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C056', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C056', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C026', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C026', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C026', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C026', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C026', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C045', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C045', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C045', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C045', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C045', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C009', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C009', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C009', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C009', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C009', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C016', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C016', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C016', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C016', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C016', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C040', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C040', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C040', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C040', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C040', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C023', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C023', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C023', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C023', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C023', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C053', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C053', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C053', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C053', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C053', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C060', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C060', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C060', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C060', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C060', 2, 'UI/UX', 0),
  ('kunal.Shah@realvision.com', 'C054', 2, 'Innovation', 0),
  ('kunal.Shah@realvision.com', 'C054', 2, 'Functionality', 0),
  ('kunal.Shah@realvision.com', 'C054', 2, 'Presentation', 0),
  ('kunal.Shah@realvision.com', 'C054', 2, 'Feasibility', 0),
  ('kunal.Shah@realvision.com', 'C054', 2, 'UI/UX', 0),
  ('sagar@dextralabs.com', 'C012', 1, 'Innovation', 8),
  ('sagar@dextralabs.com', 'C012', 1, 'Functionality', 7),
  ('sagar@dextralabs.com', 'C012', 1, 'Presentation', 7),
  ('sagar@dextralabs.com', 'C012', 1, 'Feasibility', 5),
  ('sagar@dextralabs.com', 'C012', 1, 'UI/UX', 8),
  ('sagar@dextralabs.com', 'C008', 1, 'Innovation', 8),
  ('sagar@dextralabs.com', 'C008', 1, 'Functionality', 6),
  ('sagar@dextralabs.com', 'C008', 1, 'Presentation', 7),
  ('sagar@dextralabs.com', 'C008', 1, 'Feasibility', 6),
  ('sagar@dextralabs.com', 'C008', 1, 'UI/UX', 8),
  ('sagar@dextralabs.com', 'C020', 1, 'Innovation', 7),
  ('sagar@dextralabs.com', 'C020', 1, 'Functionality', 6),
  ('sagar@dextralabs.com', 'C020', 1, 'Presentation', 7),
  ('sagar@dextralabs.com', 'C020', 1, 'Feasibility', 8),
  ('sagar@dextralabs.com', 'C020', 1, 'UI/UX', 10),
  ('sagar@dextralabs.com', 'C026', 1, 'Innovation', 8),
  ('sagar@dextralabs.com', 'C026', 1, 'Functionality', 7),
  ('sagar@dextralabs.com', 'C026', 1, 'Presentation', 7),
  ('sagar@dextralabs.com', 'C026', 1, 'Feasibility', 9),
  ('sagar@dextralabs.com', 'C026', 1, 'UI/UX', 7),
  ('sagar@dextralabs.com', 'C038', 1, 'Innovation', 7),
  ('sagar@dextralabs.com', 'C038', 1, 'Functionality', 5),
  ('sagar@dextralabs.com', 'C038', 1, 'Presentation', 6),
  ('sagar@dextralabs.com', 'C038', 1, 'Feasibility', 6),
  ('sagar@dextralabs.com', 'C038', 1, 'UI/UX', 6),
  ('sagar@dextralabs.com', 'C050', 1, 'Innovation', 9),
  ('sagar@dextralabs.com', 'C050', 1, 'Functionality', 7),
  ('sagar@dextralabs.com', 'C050', 1, 'Presentation', 6),
  ('sagar@dextralabs.com', 'C050', 1, 'Feasibility', 7),
  ('sagar@dextralabs.com', 'C050', 1, 'UI/UX', 7),
  ('sagar@dextralabs.com', 'C056', 1, 'Innovation', 8),
  ('sagar@dextralabs.com', 'C056', 1, 'Functionality', 7),
  ('sagar@dextralabs.com', 'C056', 1, 'Presentation', 8),
  ('sagar@dextralabs.com', 'C056', 1, 'Feasibility', 9),
  ('sagar@dextralabs.com', 'C056', 1, 'UI/UX', 9),
  ('sagar@dextralabs.com', 'C019', 2, 'Innovation', 4),
  ('sagar@dextralabs.com', 'C019', 2, 'Functionality', 5),
  ('sagar@dextralabs.com', 'C019', 2, 'Presentation', 4),
  ('sagar@dextralabs.com', 'C019', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C019', 2, 'UI/UX', 4),
  ('sagar@dextralabs.com', 'C001', 2, 'Innovation', 1),
  ('sagar@dextralabs.com', 'C001', 2, 'Functionality', 3),
  ('sagar@dextralabs.com', 'C001', 2, 'Presentation', 5),
  ('sagar@dextralabs.com', 'C001', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C001', 2, 'UI/UX', 3),
  ('sagar@dextralabs.com', 'C056', 2, 'Innovation', 3),
  ('sagar@dextralabs.com', 'C056', 2, 'Functionality', 2),
  ('sagar@dextralabs.com', 'C056', 2, 'Presentation', 3),
  ('sagar@dextralabs.com', 'C056', 2, 'Feasibility', 3),
  ('sagar@dextralabs.com', 'C056', 2, 'UI/UX', 5),
  ('sagar@dextralabs.com', 'C026', 2, 'Innovation', 1),
  ('sagar@dextralabs.com', 'C026', 2, 'Functionality', 2),
  ('sagar@dextralabs.com', 'C026', 2, 'Presentation', 2),
  ('sagar@dextralabs.com', 'C026', 2, 'Feasibility', 2),
  ('sagar@dextralabs.com', 'C026', 2, 'UI/UX', 2),
  ('sagar@dextralabs.com', 'C045', 2, 'Innovation', 7),
  ('sagar@dextralabs.com', 'C045', 2, 'Functionality', 6),
  ('sagar@dextralabs.com', 'C045', 2, 'Presentation', 6),
  ('sagar@dextralabs.com', 'C045', 2, 'Feasibility', 7),
  ('sagar@dextralabs.com', 'C045', 2, 'UI/UX', 6),
  ('sagar@dextralabs.com', 'C009', 2, 'Innovation', 3),
  ('sagar@dextralabs.com', 'C009', 2, 'Functionality', 2),
  ('sagar@dextralabs.com', 'C009', 2, 'Presentation', 4),
  ('sagar@dextralabs.com', 'C009', 2, 'Feasibility', 5),
  ('sagar@dextralabs.com', 'C009', 2, 'UI/UX', 6),
  ('sagar@dextralabs.com', 'C016', 2, 'Innovation', 4),
  ('sagar@dextralabs.com', 'C016', 2, 'Functionality', 3),
  ('sagar@dextralabs.com', 'C016', 2, 'Presentation', 3),
  ('sagar@dextralabs.com', 'C016', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C016', 2, 'UI/UX', 5),
  ('sagar@dextralabs.com', 'C040', 2, 'Innovation', 1),
  ('sagar@dextralabs.com', 'C040', 2, 'Functionality', 1),
  ('sagar@dextralabs.com', 'C040', 2, 'Presentation', 3),
  ('sagar@dextralabs.com', 'C040', 2, 'Feasibility', 2),
  ('sagar@dextralabs.com', 'C040', 2, 'UI/UX', 3),
  ('sagar@dextralabs.com', 'C023', 2, 'Innovation', 1),
  ('sagar@dextralabs.com', 'C023', 2, 'Functionality', 2),
  ('sagar@dextralabs.com', 'C023', 2, 'Presentation', 4),
  ('sagar@dextralabs.com', 'C023', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C023', 2, 'UI/UX', 4),
  ('sagar@dextralabs.com', 'C053', 2, 'Innovation', 3),
  ('sagar@dextralabs.com', 'C053', 2, 'Functionality', 3),
  ('sagar@dextralabs.com', 'C053', 2, 'Presentation', 5),
  ('sagar@dextralabs.com', 'C053', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C053', 2, 'UI/UX', 4),
  ('sagar@dextralabs.com', 'C060', 2, 'Innovation', 4),
  ('sagar@dextralabs.com', 'C060', 2, 'Functionality', 3),
  ('sagar@dextralabs.com', 'C060', 2, 'Presentation', 4),
  ('sagar@dextralabs.com', 'C060', 2, 'Feasibility', 4),
  ('sagar@dextralabs.com', 'C060', 2, 'UI/UX', 5),
  ('sagar@dextralabs.com', 'C054', 2, 'Innovation', 1),
  ('sagar@dextralabs.com', 'C054', 2, 'Functionality', 2),
  ('sagar@dextralabs.com', 'C054', 2, 'Presentation', 3),
  ('sagar@dextralabs.com', 'C054', 2, 'Feasibility', 3),
  ('sagar@dextralabs.com', 'C054', 2, 'UI/UX', 4),
  ('mahendra@projectx38.com', 'C003', 1, 'Innovation', 6),
  ('mahendra@projectx38.com', 'C003', 1, 'Functionality', 7),
  ('mahendra@projectx38.com', 'C003', 1, 'Presentation', 6),
  ('mahendra@projectx38.com', 'C003', 1, 'Feasibility', 8),
  ('mahendra@projectx38.com', 'C003', 1, 'UI/UX', 7),
  ('mahendra@projectx38.com', 'C027', 1, 'Innovation', 8),
  ('mahendra@projectx38.com', 'C027', 1, 'Functionality', 4),
  ('mahendra@projectx38.com', 'C027', 1, 'Presentation', 6),
  ('mahendra@projectx38.com', 'C027', 1, 'Feasibility', 6),
  ('mahendra@projectx38.com', 'C027', 1, 'UI/UX', 6),
  ('mahendra@projectx38.com', 'C015', 1, 'Innovation', 7),
  ('mahendra@projectx38.com', 'C015', 1, 'Functionality', 5),
  ('mahendra@projectx38.com', 'C015', 1, 'Presentation', 6),
  ('mahendra@projectx38.com', 'C015', 1, 'Feasibility', 5),
  ('mahendra@projectx38.com', 'C015', 1, 'UI/UX', 8),
  ('mahendra@projectx38.com', 'C021', 1, 'Innovation', 7),
  ('mahendra@projectx38.com', 'C021', 1, 'Functionality', 5),
  ('mahendra@projectx38.com', 'C021', 1, 'Presentation', 7),
  ('mahendra@projectx38.com', 'C021', 1, 'Feasibility', 6),
  ('mahendra@projectx38.com', 'C021', 1, 'UI/UX', 6),
  ('mahendra@projectx38.com', 'C009', 1, 'Innovation', 8),
  ('mahendra@projectx38.com', 'C009', 1, 'Functionality', 7),
  ('mahendra@projectx38.com', 'C009', 1, 'Presentation', 8),
  ('mahendra@projectx38.com', 'C009', 1, 'Feasibility', 9),
  ('mahendra@projectx38.com', 'C009', 1, 'UI/UX', 8),
  ('mahendra@projectx38.com', 'C033', 1, 'Innovation', 7),
  ('mahendra@projectx38.com', 'C033', 1, 'Functionality', 6),
  ('mahendra@projectx38.com', 'C033', 1, 'Presentation', 6),
  ('mahendra@projectx38.com', 'C033', 1, 'Feasibility', 8),
  ('mahendra@projectx38.com', 'C033', 1, 'UI/UX', 6),
  ('mahendra@projectx38.com', 'C039', 1, 'Innovation', 5),
  ('mahendra@projectx38.com', 'C039', 1, 'Functionality', 5),
  ('mahendra@projectx38.com', 'C039', 1, 'Presentation', 7),
  ('mahendra@projectx38.com', 'C039', 1, 'Feasibility', 7),
  ('mahendra@projectx38.com', 'C039', 1, 'UI/UX', 7),
  ('mahendra@projectx38.com', 'C045', 1, 'Innovation', 8),
  ('mahendra@projectx38.com', 'C045', 1, 'Functionality', 8),
  ('mahendra@projectx38.com', 'C045', 1, 'Presentation', 9),
  ('mahendra@projectx38.com', 'C045', 1, 'Feasibility', 9),
  ('mahendra@projectx38.com', 'C045', 1, 'UI/UX', 8),
  ('mahendra@projectx38.com', 'C051', 1, 'Innovation', 8),
  ('mahendra@projectx38.com', 'C051', 1, 'Functionality', 6),
  ('mahendra@projectx38.com', 'C051', 1, 'Presentation', 7),
  ('mahendra@projectx38.com', 'C051', 1, 'Feasibility', 9),
  ('mahendra@projectx38.com', 'C051', 1, 'UI/UX', 8),
  ('mahendra@projectx38.com', 'C057', 1, 'Innovation', 2),
  ('mahendra@projectx38.com', 'C057', 1, 'Functionality', 2),
  ('mahendra@projectx38.com', 'C057', 1, 'Presentation', 2),
  ('mahendra@projectx38.com', 'C057', 1, 'Feasibility', 4),
  ('mahendra@projectx38.com', 'C057', 1, 'UI/UX', 3),
  ('mahendra@projectx38.com', 'C019', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C019', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C019', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C019', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C019', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C001', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C001', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C001', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C001', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C001', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C056', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C056', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C056', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C056', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C056', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C026', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C026', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C026', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C026', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C026', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C045', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C045', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C045', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C045', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C045', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C009', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C009', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C009', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C009', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C009', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C016', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C016', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C016', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C016', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C016', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C040', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C040', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C040', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C040', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C040', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C023', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C023', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C023', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C023', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C023', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C053', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C053', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C053', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C053', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C053', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C060', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C060', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C060', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C060', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C060', 2, 'UI/UX', 0),
  ('mahendra@projectx38.com', 'C054', 2, 'Innovation', 0),
  ('mahendra@projectx38.com', 'C054', 2, 'Functionality', 0),
  ('mahendra@projectx38.com', 'C054', 2, 'Presentation', 0),
  ('mahendra@projectx38.com', 'C054', 2, 'Feasibility', 0),
  ('mahendra@projectx38.com', 'C054', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C004', 1, 'Innovation', 4),
  ('vijay@dextralabs.com', 'C004', 1, 'Functionality', 5),
  ('vijay@dextralabs.com', 'C004', 1, 'Presentation', 6),
  ('vijay@dextralabs.com', 'C004', 1, 'Feasibility', 6),
  ('vijay@dextralabs.com', 'C004', 1, 'UI/UX', 6),
  ('vijay@dextralabs.com', 'C010', 1, 'Innovation', 4),
  ('vijay@dextralabs.com', 'C010', 1, 'Functionality', 4),
  ('vijay@dextralabs.com', 'C010', 1, 'Presentation', 5),
  ('vijay@dextralabs.com', 'C010', 1, 'Feasibility', 6),
  ('vijay@dextralabs.com', 'C010', 1, 'UI/UX', 5),
  ('vijay@dextralabs.com', 'C058', 1, 'Innovation', 5),
  ('vijay@dextralabs.com', 'C058', 1, 'Functionality', 5),
  ('vijay@dextralabs.com', 'C058', 1, 'Presentation', 5),
  ('vijay@dextralabs.com', 'C058', 1, 'Feasibility', 3),
  ('vijay@dextralabs.com', 'C058', 1, 'UI/UX', 3),
  ('vijay@dextralabs.com', 'C046', 1, 'Innovation', 7),
  ('vijay@dextralabs.com', 'C046', 1, 'Functionality', 5),
  ('vijay@dextralabs.com', 'C046', 1, 'Presentation', 6),
  ('vijay@dextralabs.com', 'C046', 1, 'Feasibility', 7),
  ('vijay@dextralabs.com', 'C046', 1, 'UI/UX', 6),
  ('vijay@dextralabs.com', 'C022', 1, 'Innovation', 9),
  ('vijay@dextralabs.com', 'C022', 1, 'Functionality', 6),
  ('vijay@dextralabs.com', 'C022', 1, 'Presentation', 5),
  ('vijay@dextralabs.com', 'C022', 1, 'Feasibility', 6),
  ('vijay@dextralabs.com', 'C022', 1, 'UI/UX', 6),
  ('vijay@dextralabs.com', 'C040', 1, 'Innovation', 7),
  ('vijay@dextralabs.com', 'C040', 1, 'Functionality', 5),
  ('vijay@dextralabs.com', 'C040', 1, 'Presentation', 6),
  ('vijay@dextralabs.com', 'C040', 1, 'Feasibility', 7),
  ('vijay@dextralabs.com', 'C040', 1, 'UI/UX', 7),
  ('vijay@dextralabs.com', 'C052', 1, 'Innovation', 7),
  ('vijay@dextralabs.com', 'C052', 1, 'Functionality', 5),
  ('vijay@dextralabs.com', 'C052', 1, 'Presentation', 7),
  ('vijay@dextralabs.com', 'C052', 1, 'Feasibility', 7),
  ('vijay@dextralabs.com', 'C052', 1, 'UI/UX', 6),
  ('vijay@dextralabs.com', 'C016', 1, 'Innovation', 6),
  ('vijay@dextralabs.com', 'C016', 1, 'Functionality', 6),
  ('vijay@dextralabs.com', 'C016', 1, 'Presentation', 7),
  ('vijay@dextralabs.com', 'C016', 1, 'Feasibility', 6),
  ('vijay@dextralabs.com', 'C016', 1, 'UI/UX', 7),
  ('vijay@dextralabs.com', 'C019', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C019', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C019', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C019', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C019', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C001', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C001', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C001', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C001', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C001', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C056', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C056', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C056', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C056', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C056', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C026', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C026', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C026', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C026', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C026', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C045', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C045', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C045', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C045', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C045', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C009', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C009', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C009', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C009', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C009', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C016', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C016', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C016', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C016', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C016', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C040', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C040', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C040', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C040', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C040', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C023', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C023', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C023', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C023', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C023', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C053', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C053', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C053', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C053', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C053', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C060', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C060', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C060', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C060', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C060', 2, 'UI/UX', 0),
  ('vijay@dextralabs.com', 'C054', 2, 'Innovation', 0),
  ('vijay@dextralabs.com', 'C054', 2, 'Functionality', 0),
  ('vijay@dextralabs.com', 'C054', 2, 'Presentation', 0),
  ('vijay@dextralabs.com', 'C054', 2, 'Feasibility', 0),
  ('vijay@dextralabs.com', 'C054', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C005', 1, 'Innovation', 3),
  ('shounak.shetty@brinc.io', 'C005', 1, 'Functionality', 5),
  ('shounak.shetty@brinc.io', 'C005', 1, 'Presentation', 6),
  ('shounak.shetty@brinc.io', 'C005', 1, 'Feasibility', 5),
  ('shounak.shetty@brinc.io', 'C005', 1, 'UI/UX', 5),
  ('shounak.shetty@brinc.io', 'C017', 1, 'Innovation', 5),
  ('shounak.shetty@brinc.io', 'C017', 1, 'Functionality', 4),
  ('shounak.shetty@brinc.io', 'C017', 1, 'Presentation', 5),
  ('shounak.shetty@brinc.io', 'C017', 1, 'Feasibility', 5),
  ('shounak.shetty@brinc.io', 'C017', 1, 'UI/UX', 4),
  ('shounak.shetty@brinc.io', 'C013', 1, 'Innovation', 4),
  ('shounak.shetty@brinc.io', 'C013', 1, 'Functionality', 4),
  ('shounak.shetty@brinc.io', 'C013', 1, 'Presentation', 4),
  ('shounak.shetty@brinc.io', 'C013', 1, 'Feasibility', 5),
  ('shounak.shetty@brinc.io', 'C013', 1, 'UI/UX', 5),
  ('shounak.shetty@brinc.io', 'C041', 1, 'Innovation', 5),
  ('shounak.shetty@brinc.io', 'C041', 1, 'Functionality', 4),
  ('shounak.shetty@brinc.io', 'C041', 1, 'Presentation', 4),
  ('shounak.shetty@brinc.io', 'C041', 1, 'Feasibility', 4),
  ('shounak.shetty@brinc.io', 'C041', 1, 'UI/UX', 5),
  ('shounak.shetty@brinc.io', 'C029', 1, 'Innovation', 5),
  ('shounak.shetty@brinc.io', 'C029', 1, 'Functionality', 3),
  ('shounak.shetty@brinc.io', 'C029', 1, 'Presentation', 4),
  ('shounak.shetty@brinc.io', 'C029', 1, 'Feasibility', 6),
  ('shounak.shetty@brinc.io', 'C029', 1, 'UI/UX', 5),
  ('shounak.shetty@brinc.io', 'C023', 1, 'Innovation', 6),
  ('shounak.shetty@brinc.io', 'C023', 1, 'Functionality', 5),
  ('shounak.shetty@brinc.io', 'C023', 1, 'Presentation', 5),
  ('shounak.shetty@brinc.io', 'C023', 1, 'Feasibility', 6),
  ('shounak.shetty@brinc.io', 'C023', 1, 'UI/UX', 5),
  ('shounak.shetty@brinc.io', 'C035', 1, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C035', 1, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C035', 1, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C035', 1, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C035', 1, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C053', 1, 'Innovation', 2),
  ('shounak.shetty@brinc.io', 'C053', 1, 'Functionality', 5),
  ('shounak.shetty@brinc.io', 'C053', 1, 'Presentation', 7),
  ('shounak.shetty@brinc.io', 'C053', 1, 'Feasibility', 5),
  ('shounak.shetty@brinc.io', 'C053', 1, 'UI/UX', 6),
  ('shounak.shetty@brinc.io', 'C019', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C019', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C019', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C019', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C019', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C001', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C001', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C001', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C001', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C001', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C056', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C056', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C056', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C056', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C056', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C026', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C026', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C026', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C026', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C026', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C045', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C045', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C045', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C045', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C045', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C009', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C009', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C009', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C009', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C009', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C016', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C016', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C016', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C016', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C016', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C040', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C040', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C040', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C040', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C040', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C023', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C023', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C023', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C023', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C023', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C053', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C053', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C053', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C053', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C053', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C060', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C060', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C060', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C060', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C060', 2, 'UI/UX', 0),
  ('shounak.shetty@brinc.io', 'C054', 2, 'Innovation', 0),
  ('shounak.shetty@brinc.io', 'C054', 2, 'Functionality', 0),
  ('shounak.shetty@brinc.io', 'C054', 2, 'Presentation', 0),
  ('shounak.shetty@brinc.io', 'C054', 2, 'Feasibility', 0),
  ('shounak.shetty@brinc.io', 'C054', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C014', 1, 'Innovation', 5),
  ('wagh.atharva14@gmail.com', 'C014', 1, 'Functionality', 5),
  ('wagh.atharva14@gmail.com', 'C014', 1, 'Presentation', 4),
  ('wagh.atharva14@gmail.com', 'C014', 1, 'Feasibility', 4),
  ('wagh.atharva14@gmail.com', 'C014', 1, 'UI/UX', 6),
  ('wagh.atharva14@gmail.com', 'C048', 1, 'Innovation', 4),
  ('wagh.atharva14@gmail.com', 'C048', 1, 'Functionality', 4),
  ('wagh.atharva14@gmail.com', 'C048', 1, 'Presentation', 7),
  ('wagh.atharva14@gmail.com', 'C048', 1, 'Feasibility', 6),
  ('wagh.atharva14@gmail.com', 'C048', 1, 'UI/UX', 5),
  ('wagh.atharva14@gmail.com', 'C018', 1, 'Innovation', 5),
  ('wagh.atharva14@gmail.com', 'C018', 1, 'Functionality', 5),
  ('wagh.atharva14@gmail.com', 'C018', 1, 'Presentation', 5),
  ('wagh.atharva14@gmail.com', 'C018', 1, 'Feasibility', 5),
  ('wagh.atharva14@gmail.com', 'C018', 1, 'UI/UX', 5),
  ('wagh.atharva14@gmail.com', 'C030', 1, 'Innovation', 6),
  ('wagh.atharva14@gmail.com', 'C030', 1, 'Functionality', 4),
  ('wagh.atharva14@gmail.com', 'C030', 1, 'Presentation', 6),
  ('wagh.atharva14@gmail.com', 'C030', 1, 'Feasibility', 6),
  ('wagh.atharva14@gmail.com', 'C030', 1, 'UI/UX', 5),
  ('wagh.atharva14@gmail.com', 'C036', 1, 'Innovation', 4),
  ('wagh.atharva14@gmail.com', 'C036', 1, 'Functionality', 4),
  ('wagh.atharva14@gmail.com', 'C036', 1, 'Presentation', 5),
  ('wagh.atharva14@gmail.com', 'C036', 1, 'Feasibility', 5),
  ('wagh.atharva14@gmail.com', 'C036', 1, 'UI/UX', 4),
  ('wagh.atharva14@gmail.com', 'C054', 1, 'Innovation', 7),
  ('wagh.atharva14@gmail.com', 'C054', 1, 'Functionality', 5),
  ('wagh.atharva14@gmail.com', 'C054', 1, 'Presentation', 6),
  ('wagh.atharva14@gmail.com', 'C054', 1, 'Feasibility', 8),
  ('wagh.atharva14@gmail.com', 'C054', 1, 'UI/UX', 7),
  ('wagh.atharva14@gmail.com', 'C060', 1, 'Innovation', 9),
  ('wagh.atharva14@gmail.com', 'C060', 1, 'Functionality', 7),
  ('wagh.atharva14@gmail.com', 'C060', 1, 'Presentation', 7),
  ('wagh.atharva14@gmail.com', 'C060', 1, 'Feasibility', 8),
  ('wagh.atharva14@gmail.com', 'C060', 1, 'UI/UX', 8),
  ('wagh.atharva14@gmail.com', 'C042', 1, 'Innovation', 8),
  ('wagh.atharva14@gmail.com', 'C042', 1, 'Functionality', 5),
  ('wagh.atharva14@gmail.com', 'C042', 1, 'Presentation', 4),
  ('wagh.atharva14@gmail.com', 'C042', 1, 'Feasibility', 3),
  ('wagh.atharva14@gmail.com', 'C042', 1, 'UI/UX', 3),
  ('wagh.atharva14@gmail.com', 'C024', 1, 'Innovation', 6),
  ('wagh.atharva14@gmail.com', 'C024', 1, 'Functionality', 5),
  ('wagh.atharva14@gmail.com', 'C024', 1, 'Presentation', 6),
  ('wagh.atharva14@gmail.com', 'C024', 1, 'Feasibility', 6),
  ('wagh.atharva14@gmail.com', 'C024', 1, 'UI/UX', 7),
  ('wagh.atharva14@gmail.com', 'C019', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C019', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C019', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C019', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C019', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C001', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C001', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C001', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C001', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C001', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C056', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C056', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C056', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C056', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C056', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C026', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C026', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C026', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C026', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C026', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C045', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C045', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C045', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C045', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C045', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C009', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C009', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C009', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C009', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C009', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C016', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C016', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C016', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C016', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C016', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C040', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C040', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C040', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C040', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C040', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C023', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C023', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C023', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C023', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C023', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C053', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C053', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C053', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C053', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C053', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C060', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C060', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C060', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C060', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C060', 2, 'UI/UX', 0),
  ('wagh.atharva14@gmail.com', 'C054', 2, 'Innovation', 0),
  ('wagh.atharva14@gmail.com', 'C054', 2, 'Functionality', 0),
  ('wagh.atharva14@gmail.com', 'C054', 2, 'Presentation', 0),
  ('wagh.atharva14@gmail.com', 'C054', 2, 'Feasibility', 0),
  ('wagh.atharva14@gmail.com', 'C054', 2, 'UI/UX', 0)
), mapped AS (
  SELECT j.id AS judge_id, t.id AS team_id, src.round, c.id AS criteria_id, src.score
  FROM src
  JOIN judges j ON btrim(lower(j.email)) = btrim(lower(src.judge_email))
  JOIN teams t ON t.team_code = src.team_code
  JOIN criteria c ON c.name = src.criterion_name
)
INSERT INTO scores (judge_id, team_id, round, criteria_id, score)
SELECT m.judge_id, m.team_id, m.round, m.criteria_id, m.score
FROM mapped m
WHERE NOT EXISTS (
  SELECT 1
  FROM scores s
  WHERE s.judge_id = m.judge_id
    AND s.team_id = m.team_id
    AND s.round = m.round
    AND s.criteria_id = m.criteria_id
);

-- 10) round_results
WITH src(judge_email, team_code, round, rank) AS (
  VALUES
  ('kunal.Shah@realvision.com', 'C001', 1, 3.7),
  ('kunal.Shah@realvision.com', 'C007', 1, 4.3),
  ('kunal.Shah@realvision.com', 'C011', 1, 4.8),
  ('kunal.Shah@realvision.com', 'C019', 1, 3.6),
  ('kunal.Shah@realvision.com', 'C025', 1, 3.8),
  ('kunal.Shah@realvision.com', 'C031', 1, 7.6),
  ('kunal.Shah@realvision.com', 'C037', 1, 6.5),
  ('kunal.Shah@realvision.com', 'C043', 1, 5.2),
  ('kunal.Shah@realvision.com', 'C055', 1, 5.5),
  ('sagar@dextralabs.com', 'C008', 1, 4.3),
  ('sagar@dextralabs.com', 'C012', 1, 4),
  ('sagar@dextralabs.com', 'C020', 1, 3.9),
  ('sagar@dextralabs.com', 'C026', 1, 3.3),
  ('sagar@dextralabs.com', 'C038', 1, 6.5),
  ('sagar@dextralabs.com', 'C050', 1, 3.9),
  ('sagar@dextralabs.com', 'C056', 1, 2.1),
  ('mahendra@projectx38.com', 'C003', 1, 5.6),
  ('mahendra@projectx38.com', 'C009', 1, 2.3),
  ('mahendra@projectx38.com', 'C015', 1, 6.4),
  ('mahendra@projectx38.com', 'C021', 1, 6.5),
  ('mahendra@projectx38.com', 'C027', 1, 6.9),
  ('mahendra@projectx38.com', 'C033', 1, 6.1),
  ('mahendra@projectx38.com', 'C039', 1, 6.3),
  ('mahendra@projectx38.com', 'C045', 1, 1.8),
  ('mahendra@projectx38.com', 'C051', 1, 3.1),
  ('mahendra@projectx38.com', 'C057', 1, 10),
  ('vijay@dextralabs.com', 'C004', 1, 5.3),
  ('vijay@dextralabs.com', 'C010', 1, 7),
  ('vijay@dextralabs.com', 'C016', 1, 3),
  ('vijay@dextralabs.com', 'C022', 1, 3.9),
  ('vijay@dextralabs.com', 'C040', 1, 3.1),
  ('vijay@dextralabs.com', 'C046', 1, 3.7),
  ('vijay@dextralabs.com', 'C052', 1, 3.2),
  ('vijay@dextralabs.com', 'C058', 1, 6.8),
  ('shounak.shetty@brinc.io', 'C005', 1, 3.7),
  ('shounak.shetty@brinc.io', 'C013', 1, 4.9),
  ('shounak.shetty@brinc.io', 'C017', 1, 4.6),
  ('shounak.shetty@brinc.io', 'C023', 1, 2.4),
  ('shounak.shetty@brinc.io', 'C029', 1, 4.3),
  ('shounak.shetty@brinc.io', 'C035', 1, 8),
  ('shounak.shetty@brinc.io', 'C041', 1, 5),
  ('shounak.shetty@brinc.io', 'C053', 1, 3.1),
  ('wagh.atharva14@gmail.com', 'C014', 1, 6.2),
  ('wagh.atharva14@gmail.com', 'C018', 1, 5.9),
  ('wagh.atharva14@gmail.com', 'C024', 1, 3.8),
  ('wagh.atharva14@gmail.com', 'C030', 1, 5.3),
  ('wagh.atharva14@gmail.com', 'C036', 1, 7.5),
  ('wagh.atharva14@gmail.com', 'C042', 1, 6.5),
  ('wagh.atharva14@gmail.com', 'C048', 1, 5.6),
  ('wagh.atharva14@gmail.com', 'C054', 1, 3),
  ('wagh.atharva14@gmail.com', 'C060', 1, 1.2)
), mapped AS (
  SELECT j.id AS judge_id, t.id AS team_id, src.round, src.rank
  FROM src
  JOIN judges j ON btrim(lower(j.email)) = btrim(lower(src.judge_email))
  JOIN teams t ON t.team_code = src.team_code
)
INSERT INTO round_results (judge_id, team_id, round, rank)
SELECT m.judge_id, m.team_id, m.round, m.rank
FROM mapped m
WHERE NOT EXISTS (
  SELECT 1
  FROM round_results rr
  WHERE rr.judge_id = m.judge_id
    AND rr.team_id = m.team_id
    AND rr.round = m.round
);

COMMIT;
